openapi: 3.0.0
info:
  version: "0.1.0"
  title: Doot SMS API
  description: An API to send messages programatically from your phones.

paths:
  /mailer/message:
    post:
      summary: Sends a message to the Number
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Message"

      responses:
        200:
          description: Successfully recorded message to send in future.
        400:
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SendError"

  /mailer/broadcast:
    post:
      summary: Send same message to multiple phone numbers
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Broadcast"
      responses:
        200:
          description: Messages recorded to be sent when carriers available.
        400:
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BroadcastError"

  /carrier/messages:
    get:
      summary: Get unsent messages to send
      responses:
        200:
          description: Messages to send
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UniqueMessages"
  /carrier/sent:
    post:
      summary: Mark these messages as sent
      responses:
        200:
          description: Successfully marked messages as sent
        400:
          description: Invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sent:
                    $ref: '#/components/schemas/Ids'

components:
  schemas:
    Phone:
      type: object
      required:
        - country
        - num
      properties:
        country:
          type: integer
          example: 91
        num:
          type: string
          example: "1234567890"
    Text:
      type: string
      example: "Hi! how are you?"
    Id:
      type: integer
      example: 1
    Message:
      type: object
      required:
        - phone
        - text
      properties:
        phone:
          $ref: "#/components/schemas/Phone"
        text:
          $ref: "#/components/schemas/Text"
    UniqueMessage:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Id'
        phone:
          $ref: "#/components/schemas/Phone"
        text:
          $ref: "#/components/schemas/Text"


    Phones:
      type: array
      items:
        $ref: "#/components/schemas/Phone"
    Texts:
      type: array
      items:
        $ref: "#/components/schemas/Text"
    Ids:
      type: array
      items:
        $ref: "#/components/schemas/Id"
      example: [1 , 2, 4]
    
    Messages:
      type: array
      items:
        $ref: "#/components/schemas/Message"
    UniqueMessages:
      type: array
      items:
        $ref: "#/components/schemas/UniqueMessage"

    Broadcast:
      type: object
      properties:
        phones:
          $ref: "#/components/schemas/Phones"
        text:
          $ref: "#/components/schemas/Text"

    SendError:
      type: object
      properties:
        error:
          type: object
          properties:
            phone:
              type: string
              example: "None of your carriers can send to this number"
            text:
              type: string
              example: "Message too long"
    BroadcastError:
      type: object
      properties:
        error:
          type: object
          properties:
            phones:
              type: array
              items:
                type: object
                properties:
                  phone:
                    $ref: "#/components/schemas/Phone"
                  error:
                    type: string
                    example: "Invalid phone number"
            text:
              type: string
              example: "Message too long"
